/** @file */

#ifndef TAGS_H
#define TAGS_H

#include <string>

/** This file containt Macro for checking the constraints */

#define SOLUTION_ADMISSIBLE 1
#define SHIFT_ADMISSIBLE 2
#define OPERATION_ADMISSIBLE 3

/** Drivers */
#define DRI01_INTER_SHIFTS_DURATION 11
#define DRI03_RESPECT_OF_MAXIMAL_DRIVING_TIME 12
#define DRI08_TIME_WINDOWS_OF_THE_DRIVERS 13

/** Trailers */
#define TL01_DIFFERENT_SHIFTS_OF_THE_SAME_TRAILER_CANNOT_OVERLAP_IN_TIME 21
#define TL03_THE_TRAILER_ATTACHED_TO_A_DRIVER_IN_A_SHIFT_MUST_BE_COMPATIBLE 22

/** Sites */
#define DYN01_RESPECT_OF_TANK_CAPACITY_FOR_EACH_SITE 31 /// At Operation

/** Shifts */
#define SHI02_ARRIVAL_AT_A_POINT_REQUIRES_TRAVELING_TIME_FROM_PREVIOUS_POINT 41
#define SHI03_LOADING_AND_DELIVERY_OPERATIONS_TAKE_A_CONSTANT_TIME 42
#define SHI05_DELIVERY_OPERATIONS_REQUIRE_THE_CUSTOMER_SITE_TO_BE_ACCESSIBLE_FOR_THE_TRAILER 43  /// At Operation
#define SHI06_TRAILERQUANTITY_CANNOT_BE_NEGATIVE_OR_EXCEED_CAPACITY_OF_THE_TRAILER 44  /// At Operation
#define SHI07_INITIAL_QUANTITY_OF_A_TRAILER_FOR_A_SHIFT_IS_THE_END_QUANTITY_OF_THE_TRAILER_FOLLOWING_THE_PREVIOUS_SHIFT 45 // At Solution
#define SHI11_SOME_PRODUCT_MUST_BE_LOADED_OR_DELIVERED 46

/** Quality of service */
#define QS02_RUN_OUT_AVOIDANCE 51

/** Information Macros */
#define ERROR_NOT_ADMISSIBLE 0
#define TODO_MACRO -10

namespace rip {
namespace tags {

std::string get_string(int i);

} // namespace tags
} // namespace rip

#endif // TAGS_H